apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-backup
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjob-elasticsearch-backup"
        spec:
          containers:
          - name: elasticsearch-backup
            image: bash
            command: ["bash",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: OnFailure 
