apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elk-restore
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany 
  nfs: 
    server:    172.24.20.34
    path:      /var/nfs
  persistentVolumeReclaimPolicy: Recycle
