apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: pvc-elk-restore
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
