apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    creationTimestamp: null
    labels:
      template: logging-es-snapshot-clean
    name: logging-es-snapshot-clean
  spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 5
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            activeDeadlineSeconds: 500
            containers:
            - command:
              - /bin/bash
              - -c
              - sh -x /scripts/clean-snapshots.sh
              image: registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7:latest
              imagePullPolicy: Always
              name: logging-es-snapshot-clean
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/elasticsearch/secret
                  name: elasticsearch
                  readOnly: true
                - mountPath: /scripts
                  name: logging-es-snapshot-config 
                  readOnly: true
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            nodeSelector:
              region: infra
            volumes:
              - name: elasticsearch
                secret:
                  defaultMode: 420
                  secretName: logging-elasticsearch
              - configMap: 
                  defaultMode: 0770
                  name: logging-es-snapshot-config 
                name: logging-es-snapshot-config 
    schedule: '@midnight'
    #schedule: '*/1 * * * *'
    #schedule: '00 * * * *'
    successfulJobsHistoryLimit: 5
    suspend: false
  status:
    lastScheduleTime: 2019-10-20T00:00:00Z
kind: List
metadata: {}
